### ISSUE TITLE
Create error bars with custom `dataComponents`

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-examples#11]
Should compose VictoryLine and VictoryScatter, and supply a `dataComponent` prop for VictoryScatter so that error bars show up.

![image](https://cloud.githubusercontent.com/assets/3719995/15029494/aace521a-1202-11e6-91b7-300cc9a2b7a0.png)

**Comment by stefvhuynh** [comment]
https://github.com/FormidableLabs/victory-examples/pull/14

**Comment by chrisbolin** [comment]
Closed PR w/o merge
