### ISSUE TITLE
Move This Repo To Victory-Docs (then delete this)

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/victory-examples#23]
`<CustomTheme />` example lives in `/src`. Both `/docs` and `/demo` refer to it—this follows the directory structure of other victory components but it’s starting to feel a little weird. 

We may not need `/demo` anymore as one could run `builder run docs-dev` and see essentially the same thing. Would it be okay to kill `/demo` folder in favor of `/src` and `/docs`?

**Comment by paulathevalley** [comment]
On further discussion with @chrisbolin, the `src/` files are almost identical to the `ecology.md` files, which feels overcomplicated. We’d like to make this better. 

So, this boils down to this question: what really is the example, the _source_ (`src/candlestick-dashboard.js`) or the _tutorial_ (`ecology.md`)? 

1. If the _tutorial_ is held sacred, we propose to nuke this repo, and move the `ecology.md` files over to `victory-docs`. 

2. If the _source_ is held sacred, we propose to nuke the `/docs` and write a script "injecting" the source file (e.g. `src/candlestick-dashboard.js`) into `ecology.md`. This option would require some standardization of the examples, for instance: a title (required), explanation (optional), and component (required, only one allowed). This also means the examples are less flexible. 

@boygirl what do you think?

**Comment by chrisbolin** [comment]
Well summarized @paulathevalley. I vote for *Option 1.*

**Comment by chrisbolin** [comment]
I would add that it's very tough currently to _test these examples in the context of the Victory Docs site_. Option 1 would completely ameliorate that. Option 2 would let us at least `npm link` if we exported the examples.

**Comment by ebrillhart** [comment]
@paulathevalley I vote option 1 unless @boygirl is attached to hanging onto victory-examples

**Comment by boygirl** [comment]
I'm in favor of option 1 but only if we can make victory-docs public. We have a bunch of stuff in the docs link back to source code, so it needs to live in a public repo.

**Comment by chrisbolin** [comment]
I'll take this on. I'm first going to make the docs repo public, https://github.com/FormidableLabs/victory-docs/issues/51

**Comment by chrisbolin** [comment]
is everyone ok removing this repo? I've tried a few things trying to find links to this...
* `grep -R "github.com/FormidableLabs/victory-examples" *` for all `victory-docs` dependencies and sub-deps
* https://www.npmjs.com/browse/depended/victory-examples
* Googling `"FormidableLabs/victory-examples"`

I think it'd be safe to remove. So we have to options:
A. Completely remove this repo.
B. Remove all the content and leave a note in the README pointing to `victory-docs`

What say you? @ebrillhart @boygirl @kenwheeler @paulathevalley

**Comment by chrisbolin** [comment]
We also need to think about the open issues in this repo. I'll migrate or close them, as appropriate.

**Comment by chrisbolin** [comment]
Adios, `victory-examples`
