### ISSUE TITLE
Docs: Never stack playgrounds side-by-side

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/victory-examples#28]
Request from @boygirl 

> make the recipes always stack top/bottom instead of left right
> full screen code blocks 
> don't care if they scroll

<img width="1496" alt="screen shot 2016-06-22 at 2 42 21 pm" src="https://cloud.githubusercontent.com/assets/768965/16284754/950c067e-3887-11e6-949c-feda5c7042be.png">

Hmm, this leaves two options for the scrolling behavior of the code block: 
- Scroll page to view end of code block and lose sight of playground preview  
- Scroll within code block container, perhaps losing context (as less code could be seen on the screen at one time), but potentially always be able to see (or at least quickly see) the playground preview

Alternatives: 
- ~~Adjust breakpoint to be wider so that the side-by-sides happen for wider browser windows~~
- Find out if it's possible to adjust the indent spacing—1 space instead of 2 spaces would help contract the widths of the code blocks, but it might be weird?
- Shrugs

**Comment by bmathews** [comment]
Resolved via FormidableLabs/victory-docs#48 and FormidableLabs/formidable-landers#112
