### ISSUE TITLE
each example needs a separate file

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-examples#3]
Should each example be it's own component, and should have a corresponding ecology section with component playground

**Comment by paulathevalley** [comment]
Given that each example will be complicated, my understanding is a fully-fleshed tutorial component makes most sense, meaning no ecology and component playground.  

```
.
├── demo
|   ├── tutorials
|   |   ├── multiple-axes.jsx
|   |   ├── custom-theme.jsx
|   |   └── functional-styles.jsx
|   ├── app.jsx
|   └── index.html
``` 
How about something like that?

**Comment by boygirl** [comment]
That seems right to me, but I'm not sure how this will be published yet. Eventually this should be a live examples page with annotated source code (minimum) or live, editable source code if we can figure out a reasonable format to display long code blocks with component playground.
