### ISSUE TITLE
VictoryCandlestick example

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-examples#30]
![image](https://cloud.githubusercontent.com/assets/3719995/16326970/5424fa04-3980-11e6-9d74-50079ec7d3af.png)

It doesn't have to look exactly like that, but it should be kind of dashboard like and show several things at once. Should have some interactivity

**Comment by ebrillhart** [comment]
- [ ] add upper/lower average bounds via victory area

**Comment by ebrillhart** [comment]
closed with https://github.com/FormidableLabs/victory-examples/pull/32
