### ISSUE TITLE
candlestick demo gets into weird states

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-examples#42]
clicking rapidly can cause the dashboard to get into a weird state
<img width="434" alt="screen shot 2016-08-04 at 9 13 32 pm" src="https://cloud.githubusercontent.com/assets/3719995/17425996/59ccb612-5a88-11e6-8017-d94e5d044ed4.png">

**Comment by chrisbolin** [comment]
migrated issue to victory-docs
