### ISSUE TITLE
Export docs.js components

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/victory-examples#46]
Since `victory-docs` is importing the `docs.js` components directly from the node modules, it makes `npm link` really hard (webpack doesn’t know what to do with symlinks, if I recall correctly). The `victory-examples` repo has a different purpose than `victory-chart` or `victory-pie`, so what are your thoughts on exporting each `docs.js` as a component for `victory-docs`, e.g. 
```js
import { docsA, docsB, docsC, etc } from "victory-examples";
```
?

@boygirl @chrisbolin

**Comment by chrisbolin** [comment]
closing, as we are going to deprecate this repo
