### ISSUE TITLE
reproduce economist chart

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-examples#9]
![image](https://cloud.githubusercontent.com/assets/3719995/15029138/2b0fccf8-1201-11e6-85d0-81406c896660.png)

**Comment by paulathevalley** [comment]
This is also already in progress in the `feature-customTheme` branch. Should I stop working on it?

**Comment by boygirl** [comment]
nope! never mind. I'll assign you instead.

**Comment by paulathevalley** [comment]
Completed!
